name: Deploy static site
on:
  push:
    branches:
      - master

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:

      - name: Pull source
        uses: actions/checkout@master

      - name: Setup node env
        uses: actions/setup-node@v2.1.2
        with:
          node-version: ${{ matrix.node }}

      - name: Install dependencies
        run: npm install

      - name: Generate
        run: npm run generate


      - name: Deploy script
        uses: peaceiris/actions-gh-pages@v3
        with:
          external_repository: andres-ortizl/andres-ortizl.github.io
          publish_branch: master
          deploy_key: ${{ secrets.KEY }}
          publish_dir: ./dist
